# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kkrnvfjq0WHpktxEkxJ9qqLK3aPeyKHt
"""

def WhoAmI():
  return 'rz2726'